Renderer:
  API: Vulkan
  ClearColor: [0.1, 0.1, 0.1, 1]
  Wireframe: false
  DepthTest: true
  DepthWrite: true
  FaceCulling: true
  Blending: true
  VSync: false
  ShowPhysicsDebugDraw: false
  ParallelMeshSubmission: false
  AnisotropicFilteringLevel: 16
  TextureFilter: Anisotropic
  CullMode: None
Physics:
  Enabled: true
  Substeps: 6
Window:
  Title: Honey Engine
  Width: 1802
  Height: 695
  PosX: 628
  PosY: 269
  Fullscreen: true